version: '2'
services:
    monolithicdemoapplication-app:
        image: monolithicdemoapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monolithicdemoapplication-mysql:3306/monolithicdemoapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=monolithicdemoapplication-elasticsearch:9300
        ports:
            - 8080:8080
    monolithicdemoapplication-mysql:
        extends:
            file: mysql.yml
            service: monolithicdemoapplication-mysql
    monolithicdemoapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: monolithicdemoapplication-elasticsearch
